### PR TITLE
move uri parsing to http.util

### PR DESCRIPTION
**Pull request by aleclarson**
I use the uri parsing logic in my own module.

### CODE REVIEW

**Comment by RyanSquared** [comment]
:+1: could also be useful elsewhere just in lua-http (perhaps proxies, headers, etc. might use it?)

**Comment by daurnimator** [comment]
huh? this is pretty much the most basic use of lpeg_patterns's uri module. You should be using that directly.

Why/when else would you need the http or ws scheme check? Why would you discard path?

Also, this breaks lua-http when passing in a string to `new_from_uri`

**Comment by aleclarson** [comment]
@daurnimator whoops, sorry for the oversight. I would prefer to reuse the assertion logic, would you be fine with returning the entire table, or are you taking a hard stance that I should just copy-paste the logic?

**Comment by daurnimator** [comment]
> would you be fine with returning the entire table

I don't love the idea of functions that *sometimes* return their input. Makes it very hard to reason about mutability.

> I would prefer to reuse the assertion logic

Do you need it all though?
In most cases you'll only want: `uri_t = assert(uri_patt:match(mystring), "invalid URI")`

  - You probably have a default scheme to assume (so you don't want `local scheme = assert(uri_t.scheme, "URI missing scheme")`)
  - You probably want to accept a different set of schemes (so you don't want `assert(scheme == "https" or scheme == "http" or scheme == "ws" or scheme == "wss", "scheme not valid")`)
  - For e.g. a uri with a unix path, there is no `host` field (so you don't want the `assert(uri_t.host, "URI must include a host")`)

**Comment by aleclarson** [comment]
Okay, you convinced me. Better to keep the requirements decoupled in case different functionality is desired.

**Pull request closed without merging**
